---
title: "Introduction"
teaching: 5
exercises: 0
---
:::::::::::::::::::::::::::::::::::::: questions
- What is this all about?
::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives
- Explain the general structure of this introductory course
- Explain how to submit "homework" assignments
::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction
This is the accompanying website to the Empra Differentielle Psychologie of Heidelberg University. It is authored and used by [Sven Lesche](https://www.psychologie.uni-heidelberg.de/person/sven-lesche). This course aims to cover:

- Some R basics and how to structure code
- Getting a first glimpse of data
- Cleaning data
- Running some analysis

## Lesson Structure
The entire course is organized in short "Episodes" intended to take around 10-15mins to read and around 5-10mins to complete the challenges below. You will complete approximately one episode per week.
At the end of each episode, you will upload a script containing the solutions to the challenges.
The file format should be: `lessonnumber_solutions_name_surname.R`.
Upload the script containing your solutions to a HeiBox folder and share that folder with me.

## A word about Chat-GPT
Chat-GPT is an amazing tool that makes it much easier to just try something out. Importantly, it can take a lot of work off your hands, especially early on in your learning process. Most of the challenges here can just be solved by plugging them into a LLM like Chat-GPT. I encourage you to first try to find a solution yourself. You will learn a lot more by failing yourself first and continuing to try.

Nonetheless, sometimes it may be necessary to ask Chat-GPT or google a solution. In real data analysis, this is done a lot! Nobody knows anything. However, the most important thing for now is that you *understand* the code you write. Thus, if you use Chat-GPT, make it explain to you why this code works and what it is doing or ask it for hints instead of the solution.

## Accompanying Material
This course relies heavily on [R for Data Science (2e)](https://r4ds.hadley.nz/), which can be treated as an accompanying textbook.

## Questions & Support
This is the first version of the new course material. If you have any questions or notice any inconsistencies / opportunities for improvement, feel free to reach out to to me via mail or Slack. If you feel comfortable using GitHub, also feel free to submit an [issue](https://github.com/SLesche/r-for-empra/issues).

Some opportunities for improvement are:

- Is the material sufficiently explained? Can you follow?
- Are the exercises too difficult / not enough to practice material learned in an episode?
- Are you missing any information to complete following episodes?
- Is there information missing or information that you do not require?
- Are there any typos / wrong examples?
- Whatever else comes to mind.

Feel free to reach out to me via any of the channels with your feedback. I will try to implement it as soon as possible.
Thank you for your help in making this course better for coming students!

::::::::::::::::::::::::::::::::::::: keypoints
- Follow the structured outline to learn R basics and data analysis
- Submit weekly scripts following the specified format
- Contact me via mail or Slack for any queries
::::::::::::::::::::::::::::::::::::::::::::::::
