---
title: "Packages in R"
teaching: 10
exercises: 4
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is an R package?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Explain how to use R packages
- Explain how to use `library()` and the `::` operator

::::::::::::::::::::::::::::::::::::::::::::::::

## R Packages

It is possible to add functions to R by writing a package, or by obtaining a package written by someone else. As of this writing, there are over 7,000 packages available on CRAN (the comprehensive R archive network). R and RStudio have functionality for managing packages:

* You can see what packages are installed by typing `installed.packages()`
* You can install packages by typing `install.packages("packagename")`, where `packagename` is the package name, in quotes.
* You can update installed packages by typing `update.packages()`
* You can remove a package with `remove.packages("packagename")`
* You can make a package available for use with `library(packagename)`
* You can use a function from a package without loading it entirely using `packagename::functionname()`

### Demonstration

```{r}
# Installing a package
install.packages("dplyr")

# Loading a package
library(dplyr)

# Using a function without loading the entire package
dplyr::glimpse(mtcars)
```

### Why use `::`?
- Using `::` allows access to a specific function without attaching the entire package.
- This can help avoid function name conflicts between different packages.
- It is useful for one-off function calls where loading the full package is unnecessary.

::: challenge
## Challenge 1:

:::

::: keypoints
- R packages are "add-ons" to R, they provide useful new tools.
- Install a package using `install.packages("packagename")`.
- Use a package using `library(packagename)` at the beginning of your script.
- Use `::` to access specific functions from a package without loading it entirely.
:::

