---
title: 'Projects'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is an R project? 
- How do projects help me organize my scripts.

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Explain how projects can provide structure
- Explain what a "working directory" is and how to access files

::::::::::::::::::::::::::::::::::::::::::::::::

## Working Directory
It is very important that you keep your files somewhat orderly. This is important both for us humans to understand, but also for computers. 

## Saving Data

::: callout
## A word about `setwd()`

:::

## Projects in R




## Challenges
::: challenge
## Challenge 1:

(Project was created already)
Script with vector creation. Save it with variable name.
:::

::: challenge
## Challenge 2: 

Some basic computation with this vector
:::

::: challenge
## Challenge 3: 

Where am I?
Save this vector in a subfolder called data
(you may need to create this folder first)
:::

::: challenge
## Challenge 4: Storing data
:::

::: challenge
## Challenge 5: Get a list of available files
Use list.files() to figure something out
:::

::: challenge 
## Challenge 6:
Create a new script for next episode. Save this with an appropriate name

In this script. Load the packages `dplyr` and ggplot
:::


::::::::::::::::::::::::::::::::::::: keypoints 

- 

::::::::::::::::::::::::::::::::::::::::::::::::
