---
title: 'Using R Scripts and R Projects'
teaching: 15
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- How do you use scripts in R to document your work?
- How can you organize scripts effectively?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Show how to use scripts to generate reproducible analyses
- Explain how projects can provide structure
- Explain what a "working directory" is and how to access files

::::::::::::::::::::::::::::::::::::::::::::::::

## Scripts in R
For now, we have been only using the R console to execute commands.
This works great if there are some quick calculations you have to run, but unsuited for more complex analyses. If you want to reproduce the exact steps you took in data cleaning and analyses, you need to write them down - like a recipe. 

This is where R scripts come in. They are basically like a text file (similar to Word) where you can write down all the steps you took. This makes it possible to retrace them and produce the exact same result over and over again.

In order to use R scripts effectively, you need to do two things. Firstly, you need to write them in a way that is understandable in the future. 
We will learn more about how to write clean code in future lessons. 
Secondly (and maybe more importantly) you need to actually **save** these scripts on your computer, and ideally save them in a place where you can find them again. 
The place where you save your script and especially the place you save your data should ideally be a folder in a sensible place. For example, this script is saved in a sub-folder `episodes/` of the workshop folder `r_for_empra/`. 
This makes it easy for humans to find the script. Aim for similar clarity in your folder structure!

For this lesson, create a folder called `r_for_empra` somewhere on your computer where it makes sense for you. Then, create a new R script by clicking `File > New File > R Script` or hitting `Ctrl + Shift + N`. Save this script as  `episode_projects_and_scripts.R` in the folder `r_for_empra` created above.

## Using a script
Something about vectors

And some first functions like sum() and mean()

Maybe some indexing 

then some slicing (mean of only the first few indices)

Then some filtering (only some values greater than)

Then talk about dataframe and how they are 

## Working Directory
It is very important that you keep your files somewhat orderly. This is important both for us humans to understand, but also for computers. 

## Projects in R


::: callout
## Tip: Running segments of your code

RStudio offers you great flexibility in running code from within the editor
window. There are buttons, menu choices, and keyboard shortcuts. To run the
current line, you can 1. click on the `Run` button just above the editor panel,
or 2. select "Run Lines" from the "Code" menu, or 3. hit Ctrl-Enter in Windows
or Linux or Command-Enter on OS X. (This shortcut can also be seen by hovering
the mouse over the button). To run a block of code, select it and then `Run`.
If you have modified a line of code within a block of code you have just run,
there is no need to reselect the section and `Run`, you can use the next button
along, `Re-run the previous region`. This will run the previous code block
including the modifications you have made.

::: 

## Challenges
::: challenge
## Challenge 1:

(Project was created already)
Script with vector creation. Save it with variable name.
:::

::: challenge
## Challenge 2: 

Some basic computation with this vector
:::

::: challenge
## Challenge 3: 

Where am I?
Save this vector in a subfolder called data
(you may need to create this folder first)
:::

::: challenge
## Challenge 4: Storing data
:::

::: challenge
## Challenge 5: Get a list of available files
Use list.files() to figure something out
:::

::: challenge 
## Challenge 6:
Create a new script for next episode. Save this with an appropriate name

In this script. Load the packages `dplyr` and ggplot
:::


::::::::::::::::::::::::::::::::::::: keypoints 

- 

::::::::::::::::::::::::::::::::::::::::::::::::

